export enum sessionActionType {
    UPDATE = 'updateSession',
    ADD_MEMBERS_TO_PROJECT = 'ADD_MEMBERS_TO_PROJECT',
    REMOVE_MEMBER_FROM_PROJECT = 'REMOVE_MEMBER_FROM_PROJECT',
    UPDATE_PROJECT_MEMBER_ROLE = 'UPDATE_PROJECT_MEMBER_ROLE',
    ADD_PROJECT_TO_SESSION = 'ADD_PROJECT_TO_SESSION'
}